### PR TITLE
Fix up tests

### PR DESCRIPTION
**Pull request by philnash**
This does a bunch of things. The commits show most, but here's a summary:
- Removes test that was just calling the API helper
- Includes `minitest/mock` which is used to mock the Twilio service
- Adds success test for `/connect` endpoint
- Adds tests for the `/call` endpoint
- Tidies up some code (and whitespace, apparently)

### CODE REVIEW

**Comment by philnash** [comment]
Once this is merged, I have a pull request on top of this that upgrades to Rails 4.2.4. I'm not sure the best way to send in PRs on top of other PRs and ended up making the [PR against my own branch](https://github.com/philnash/clicktocall-rails/pull/1).

**Comment by philnash** [comment]
Anyone with a bit of time to check this out?

**Comment by jarodreyes** [comment]
:+1:

**Comment by jarodreyes** [comment]
@philnash feel free to send that upgraded branch this way. Thanks!

**Comment by philnash** [comment]
Woo, thanks! Rails upgrade pull requested @jarodreyes.

**Pull request merged**
